version: "3.9"
services:

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/[APPNAME]
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - '.env'
      
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - '.env'

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"